### ISSUE TITLE
Issues with TBA API from within the Browser

### ISSUE THREAD

**Issue by roshanr10** [fletch3555/tba-api-client-javascript#1]
When using Browserify, I had to make some small changes for it to work, is there some additional Swagger configuration that has to be changed?

The require statements here point to the local directory, however everything else is within the TBAAPI.Client folder. I had to move the ApiClient.js and index.js inside the folder to be able to even start the program. https://github.com/fletch3555/tba-api-client-javascript/blob/48b7e8113f09cf50f139c8152a8a43ec632dfdac/src/index.js#L22

Additionally, I had to comment out this block of code for it to comply with the Access-Control-Allow-Headers while using the API from within the browser.
```javascript
var contentType = this.jsonPreferredMime(contentTypes);
if (contentType) {
	// Issue with superagent and multipart/form-data (https://github.com/visionmedia/superagent/issues/746)
	if (contentType != 'multipart/form-data') {
		request.type(contentType);
	}
} else if (!request.header['Content-Type']) {
	request.type('application/json');
}

if (contentType === 'application/x-www-form-urlencoded') {
	request.send(querystring.stringify(this.normalizeParams(formParams)));
} else if (contentType == 'multipart/form-data') {
	var _formParams = this.normalizeParams(formParams);
	for (var key in _formParams) {
		if (_formParams.hasOwnProperty(key)) {
			if (this.isFileParam(_formParams[key])) {
				// file field
				request.attach(key, _formParams[key]);
			} else {
				request.field(key, _formParams[key]);
			}
		}
	}
} else if (bodyParam) {
	request.send(bodyParam);
}
```

Doing these changes got it to work, just curious if there is some swagger config that can circumvent this manual fixes.

**Comment by fletch3555** [comment]
Very good question.  I'll look into it.  The first issue may be a side-effect of my testing (I changed the namespace after the first run, but thought I caught everything before announcing this...).

**Comment by fletch3555** [comment]
Apologies for the delay.  This should be resolved now.
